### ISSUE TITLE
リリース準備 (コンテンツ)

### ISSUE THREAD

**Issue by getty708** [gdsc-osaka/official-web#13]
### Top Section
- [ ] KeyVisual下の文章
- [ ] Projects
  - [ ] Solution Challenge
  - [ ] ML Localization Project

### GDSC (Osaka)
- [ ] 「GDSC阪大支部とは？」横の文章 (見直し必要？)
- [ ] Activities
  - [ ] 画像の入れ替え
 
### Community

- [ ] Team紹介の文章 (役割 & 具体的な活動内容?)
  - [ ] Tech Team
  - [ ] Marketing Team
  - [ ] DX Team
  - [ ] Event Team
- [ ] 活動時間 & 活動場所 (活動形態)
- [ ] こんな人求めています. (内容修正する？)
- [ ] Slack参加 (文章見直し？)
- [ ] FAQ

**Comment by getty708** [comment]
## TODO: Member Page

### 運営メンバー (優先度: Mid)

- [ ] メンバーからの一言？ (Dialogの中の文章)
  -  間に合わなければ、"Coming soon ..." に変更

### 運営メンバー募集 (優先度: Low)

吉村が戦略を再検討してから更新？ (ひとまずは、現状を保つ。)

- [ ] 運営メンバーのRequirements 
- [ ] 運営メンバ採用の方針 & 説明
